image-storage:
  yandex-cloud:
    service-endpoint: **************
    signing-region:   **************
    access-key:       **************
    secret-key:       **************
    bucket-name:      **************

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
